insert into Cargo (nombre) values('ADMIN');
insert into Cargo (nombre) values('ALMACENERO');
insert into Cargo (nombre) values('GERENTE DE COMPRAS');
insert into Cargo (nombre) values('ASISTENTE DE RECIBO');

insert into Usuario (nombre, correo, contrasena, cargo_id, estado) values('admin-chorrillos', 'adminchorrillos@tailoy.com.pe', '$2a$12$LgrxVz9n0QZyDKC.KzhAe.zeB1BAXwGpj8X7LOqeoG5Qvbv./2thq', 1, 1);
insert into Usuario (nombre, correo, contrasena, cargo_id, estado) values('admin-matellini', 'adminmatellini@tailoy.com.pe', '$2a$12$LgrxVz9n0QZyDKC.KzhAe.zeB1BAXwGpj8X7LOqeoG5Qvbv./2thq', 1, 1);
insert into Usuario (nombre, correo, contrasena, cargo_id, estado) values('admin-miraflores', 'adminmiraflores@tailoy.com.pe', '$2a$12$LgrxVz9n0QZyDKC.KzhAe.zeB1BAXwGpj8X7LOqeoG5Qvbv./2thq', 1, 1);
insert into Usuario (nombre, correo, contrasena, cargo_id, estado) values('admin-pardo', 'adminpardo@tailoy.com.pe', '$2a$12$LgrxVz9n0QZyDKC.KzhAe.zeB1BAXwGpj8X7LOqeoG5Qvbv./2thq', 1, 1);
insert into Usuario (nombre, correo, contrasena, cargo_id, estado) values('admin-larco', 'adminlarco@tailoy.com.pe', '$2a$12$LgrxVz9n0QZyDKC.KzhAe.zeB1BAXwGpj8X7LOqeoG5Qvbv./2thq', 1, 1);
insert into Usuario (nombre, correo, contrasena, cargo_id, estado) values('admin-benavides', 'adminbenavides@tailoy.com.pe', '$2a$12$LgrxVz9n0QZyDKC.KzhAe.zeB1BAXwGpj8X7LOqeoG5Qvbv./2thq', 1, 1);
insert into Usuario (nombre, correo, contrasena, cargo_id, estado) values('admin-angamos', 'adminangamos@tailoy.com.pe', '$2a$12$LgrxVz9n0QZyDKC.KzhAe.zeB1BAXwGpj8X7LOqeoG5Qvbv./2thq', 1, 1);
insert into Usuario (nombre, correo, contrasena, cargo_id, estado) values('admin-barranco', 'adminbarranco@tailoy.com.pe', '$2a$12$LgrxVz9n0QZyDKC.KzhAe.zeB1BAXwGpj8X7LOqeoG5Qvbv./2thq', 1, 1);
insert into Usuario (nombre, correo, contrasena, cargo_id, estado) values('admin-magdalena', 'adminmagdalena@tailoy.com.pe', '$2a$12$LgrxVz9n0QZyDKC.KzhAe.zeB1BAXwGpj8X7LOqeoG5Qvbv./2thq', 1, 1);
insert into Usuario (nombre, correo, contrasena, cargo_id, estado) values('almacen-matellini', 'almacenmatellini@tailoy.com.pe', '$2a$12$LgrxVz9n0QZyDKC.KzhAe.zeB1BAXwGpj8X7LOqeoG5Qvbv./2thq', 2, 1);
insert into Usuario (nombre, correo, contrasena, cargo_id, estado) values('almacen-benavides', 'almacenbenavides@tailoy.com.pe', '$2a$12$LgrxVz9n0QZyDKC.KzhAe.zeB1BAXwGpj8X7LOqeoG5Qvbv./2thq', 2, 1);
insert into Usuario (nombre, correo, contrasena, cargo_id, estado) values('almacen-angamos', 'almacenangamos@tailoy.com.pe', '$2a$12$LgrxVz9n0QZyDKC.KzhAe.zeB1BAXwGpj8X7LOqeoG5Qvbv./2thq', 2, 1);
insert into Usuario (nombre, correo, contrasena, cargo_id, estado) values('almacen-miraflores', 'almacenmiraflores@tailoy.com.pe', '$2a$12$LgrxVz9n0QZyDKC.KzhAe.zeB1BAXwGpj8X7LOqeoG5Qvbv./2thq', 2, 1);
insert into Usuario (nombre, correo, contrasena, cargo_id, estado) values('almacen-chorrillos', 'almacenchorrillos@tailoy.com.pe', '$2a$12$LgrxVz9n0QZyDKC.KzhAe.zeB1BAXwGpj8X7LOqeoG5Qvbv./2thq', 2, 1);
insert into Usuario (nombre, correo, contrasena, cargo_id, estado) values('comp-chorrillos', 'compchorrillos@tailoy.com.pe', '$2a$12$LgrxVz9n0QZyDKC.KzhAe.zeB1BAXwGpj8X7LOqeoG5Qvbv./2thq', 3, 1);
insert into Usuario (nombre, correo, contrasena, cargo_id, estado) values('comp-larco', 'complarco@tailoy.com.pe', '$2a$12$LgrxVz9n0QZyDKC.KzhAe.zeB1BAXwGpj8X7LOqeoG5Qvbv./2thq', 3, 1);
insert into Usuario (nombre, correo, contrasena, cargo_id, estado) values('comp-pardo', 'comppardo@tailoy.com.pe', '$2a$12$LgrxVz9n0QZyDKC.KzhAe.zeB1BAXwGpj8X7LOqeoG5Qvbv./2thq', 3, 1);
insert into Usuario (nombre, correo, contrasena, cargo_id, estado) values('comp-magdalena', 'compmagdalena@tailoy.com.pe', '$2a$12$LgrxVz9n0QZyDKC.KzhAe.zeB1BAXwGpj8X7LOqeoG5Qvbv./2thq', 3, 1);
insert into Usuario (nombre, correo, contrasena, cargo_id, estado) values('recibo-chorrillos', 'recibochorrillos@tailoy.com.pe', '$2a$12$LgrxVz9n0QZyDKC.KzhAe.zeB1BAXwGpj8X7LOqeoG5Qvbv./2thq', 4, 1);

insert into proveedor (nombre, ruc, telefono, direccion, estado) values('FABER-CASTELL', '20100050359', '(01) 6121900', 'Av. La Molina 161, Ate 15012, Lima', 1);
insert into proveedor (nombre, ruc, telefono, direccion, estado) values('ARTESCO', '20100067324', '(01) 6180600', 'María Curie 290, Lima 15022', 1);
insert into proveedor (nombre, ruc, telefono, direccion, estado) values('PILOT/PEGAFAN', '20100069297', '(01) 6193030', 'Av. Las Águilas 160, Lima', 1);
insert into proveedor (nombre, ruc, telefono, direccion, estado) values('LAYCONSA', '20100190100', '(01) 6184200', 'Av. Nicolás Ayllón 2283, Ate 15022, Lima', 1);
insert into proveedor (nombre, ruc, telefono, direccion, estado) values('VINIFAN', '20100654025', '(511) 3134200', 'Av. Los Frutales 419, Urb. El Artesano, Ate, Lima', 1);
insert into proveedor (nombre, ruc, telefono, direccion, estado) values('TAI LOY S.A.', '20407827881', '(511) 6193030', 'Jr. Mariano Odicio 153, Surquillo, Lima', 1);
insert into proveedor (nombre, ruc, telefono, direccion, estado) values('MINERVA', '20100107563', '(01) 4455566', 'Jr. Gral. Orbegoso 207, Breña 15083, Lima', 1);
insert into proveedor (nombre, ruc, telefono, direccion, estado) values('JUSTUS', '20100047641', '(01) 4477788', 'Ca. Luisa Beausejour 2450, Lima', 1);
insert into proveedor (nombre, ruc, telefono, direccion, estado) values('HP', '20600216512', '(01) 4112000', 'Av. Las Begonias 415, San Isidro, Lima 15046', 1);
insert into proveedor (nombre, ruc, telefono, direccion, estado) values('DURACELL', '20341257167', '(01) 3814366', 'Av. Bolivia 148, Lima 15001', 1);
insert into proveedor (nombre, ruc, telefono, direccion, estado) values('MAXELL', '20516199602', '982096241', 'Jr. Niquel 240, Los Olivos 15311, Lima', 1);
insert into proveedor (nombre, ruc, telefono, direccion, estado) values('DARYZA', '20605420509', '984935971', 'Av. Argentina 3093, Callao 07001', 1);
insert into proveedor (nombre, ruc, telefono, direccion, estado) values('3M', '20543728927', '986650380', 'Av. Los Frutales 486, Lima', 1);
insert into proveedor (nombre, ruc, telefono, direccion, estado) values('GLORIA', '20467539842', '(01) 4707170', 'Av. República de Panamá 2457, Lima', 1);
insert into proveedor (nombre, ruc, telefono, direccion, estado) values('EPSON', '20486468913', '(01) 4758899', 'Jr. Toribio Ara 293, Pueblo Libre, Lima', 1);
insert into proveedor (nombre, ruc, telefono, direccion, estado) values('CANON', '20601112419', '(01) 4769933', 'Av. Chancay 184, Huaral, Lima', 1);
insert into proveedor (nombre, ruc, telefono, direccion, estado) values('CHAMEX', '20514344559', '(01) 4840000', 'Av. Los Pinos 534, Urb. Villa, Lima', 1);
insert into proveedor (nombre, ruc, telefono, direccion, estado) values('KRAFT', '20100164010', '(01) 4832211', 'Av. José Pardo 223, Miraflores, Lima', 1);
insert into proveedor (nombre, ruc, telefono, direccion, estado) values('ELITE', '20266352337', '(01) 4753322', 'Av. Santa Rosa 550, Santa Anita, Lima', 1);
insert into proveedor (nombre, ruc, telefono, direccion, estado) values('NESTLÉ', '20263322496', '(01) 4363626', 'Calle Luis Galvani 493, Ate, Lima', 1);
insert into proveedor (nombre, ruc, telefono, direccion, estado) values('PARKER', '20602272355', '(01) 4201122', 'Calle Paz Soldán 170, Int. 204, San Isidro, Lima', 1);
insert into proveedor (nombre, ruc, telefono, direccion, estado) values('REY SCOTT', '20500000001', '(01) 5555555', 'Av. Imaginaria 123, Lima', 1);
insert into proveedor (nombre, ruc, telefono, direccion, estado) values('SPLENDA', '20515346113', '(01) 4332222', 'Av. Salud 456, Lima', 1);
insert into proveedor (nombre, ruc, telefono, direccion, estado) values('TORK', '20611725486', '(044) 123456', 'Av. Túpac Amaru, El Porvenir, Trujillo', 1);
insert into proveedor (nombre, ruc, telefono, direccion, estado) values('VIRUTEX', '20492577597', '(01) 7654321', 'Av. Limpieza 789, Lima', 1);

insert into categoria (nombre) values('TECNOLOGÍA');
insert into categoria (nombre) values('ARTE Y DISEÑO');
insert into categoria (nombre) values('ESCOLAR');
insert into categoria (nombre) values('OFICINA');
insert into categoria (nombre) values('UNIVERSITARIO');
insert into categoria (nombre) values('CUIDADO PERSONAL Y LIMPIEZA');
insert into categoria (nombre) values('EMPAQUES PARA DELIVERY');
insert into categoria (nombre) values('ABARROTES');

insert into subcategoria (nombre, categoria_id) values('CÓMPUTO', 1);
insert into subcategoria (nombre, categoria_id) values('CELULARES', 1);
insert into subcategoria (nombre, categoria_id) values('ACCESORIOS DE CÓMPUTO', 1);
insert into subcategoria (nombre, categoria_id) values('ZONA GAMER', 1);
insert into subcategoria (nombre, categoria_id) values('TV Y VIDEO', 1);
insert into subcategoria (nombre, categoria_id) values('AUDIO', 1);
insert into subcategoria (nombre, categoria_id) values('FOTOGRAFÍA', 1);
insert into subcategoria (nombre, categoria_id) values('ART TECHNOLOGY', 1);
insert into subcategoria (nombre, categoria_id) values('DIBUJO', 2);
insert into subcategoria (nombre, categoria_id) values('PINTURA', 2);
insert into subcategoria (nombre, categoria_id) values('BLOCKS DE ARTE', 2);
insert into subcategoria (nombre, categoria_id) values('PINCELES Y BROCHAS', 2);
insert into subcategoria (nombre, categoria_id) values('SET DE ARTE', 2);
insert into subcategoria (nombre, categoria_id) values('TIJERAS Y CORTADORES', 2);
insert into subcategoria (nombre, categoria_id) values('PLASTILINAS Y MASILLAS', 2);
insert into subcategoria (nombre, categoria_id) values('MANUALIDADES', 2);
insert into subcategoria (nombre, categoria_id) values('ÚTILES ESCOLARES', 3);
insert into subcategoria (nombre, categoria_id) values('CUADERNOS Y BLOCKS', 3);
insert into subcategoria (nombre, categoria_id) values('MOCHILAS Y CARTUCHERAS', 3);
insert into subcategoria (nombre, categoria_id) values('PAPELERÍA ESCOLAR', 3);
insert into subcategoria (nombre, categoria_id) values('FORROS Y ETIQUETAS', 3);
insert into subcategoria (nombre, categoria_id) values('MATERIALES DIDÁCTICOS', 3);
insert into subcategoria (nombre, categoria_id) values('ARTÍCULOS DE ESCRITORIO', 4);
insert into subcategoria (nombre, categoria_id) values('PAPELERÍA DE OFICINA', 4);
insert into subcategoria (nombre, categoria_id) values('EMBALAJE Y PEGAMENTOS', 4);
insert into subcategoria (nombre, categoria_id) values('ACCESORIOS DE OFICINA', 4);
insert into subcategoria (nombre, categoria_id) values('ARCHIVO Y ORGANIZACIÓN', 4);
insert into subcategoria (nombre, categoria_id) values('MUEBLES DE OFICINA', 4);
insert into subcategoria (nombre, categoria_id) values('ESCRITURA FINA', 4);
insert into subcategoria (nombre, categoria_id) values('AGENDAS Y LIBRETAS', 4);
insert into subcategoria (nombre, categoria_id) values('CUADERNOS UNIVERSITARIOS', 5);
insert into subcategoria (nombre, categoria_id) values('CARTUCHERAS Y MOCHILAS', 5);
insert into subcategoria (nombre, categoria_id) values('PAPELERÍA UNIVERSITARIA', 5);
insert into subcategoria (nombre, categoria_id) values('TEXTOS UNIVERSITARIOS', 5);
insert into subcategoria (nombre, categoria_id) values('CUIDADO PERSONAL', 6);
insert into subcategoria (nombre, categoria_id) values('LIMPIEZA GENERAL', 6);
insert into subcategoria (nombre, categoria_id) values('PRODUCTOS DE HIGIENE', 6);
insert into subcategoria (nombre, categoria_id) values('ASPIRADO Y LIMPIEZA', 6);
insert into subcategoria (nombre, categoria_id) values('ELECTRODOMÉSTICOS DE CUIDADO', 6);
insert into subcategoria (nombre, categoria_id) values('BOLSAS Y EMPAQUES', 7);
insert into subcategoria (nombre, categoria_id) values('ENVASES DESCARTABLES', 7);
insert into subcategoria (nombre, categoria_id) values('CONTÓMETROS', 7);
insert into subcategoria (nombre, categoria_id) values('CINTAS Y EMBALAJES', 7);
insert into subcategoria (nombre, categoria_id) values('AGUAS Y BEBIDAS', 8);
insert into subcategoria (nombre, categoria_id) values('ABARROTES COMESTIBLES', 8);
insert into subcategoria (nombre, categoria_id) values('ABARROTES NO COMESTIBLES', 8);

insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1001, 'Laptop HP Pavilion 15', 'HP', 'Laptop portátil con procesador Intel i5, 8GB RAM, 512GB SSD', 1, 50, 2499.99, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1002, 'Celular Samsung Galaxy S22', 'Samsung', 'Celular con cámara de 50MP, pantalla de 6.1"', 2, 100, 899.99, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1003, 'Mouse Logitech G502', 'Logitech', 'Mouse gamer con 11 botones programables', 3, 150, 79.99, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1004, 'Auriculares Sony WH-1000XM4', 'Sony', 'Auriculares inalámbricos con cancelación de ruido', 6, 200, 349.99, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1005, 'Cámara Canon EOS 90D', 'Canon', 'Cámara digital con lente 18-135mm, resolución 32.5MP', 7, 30, 1299.99, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1006, 'Tablet Wacom Intuos Pro', 'Wacom', 'Tablet de dibujo profesional con 8192 niveles de presión', 8, 40, 379.99, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1007, 'Papel A4 Canson', 'Canson', 'Papel de alta calidad para impresión y dibujo', 9, 500, 5.99, 'Paquete', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1008, 'Set de pinceles para óleo', 'Artesco', 'Set completo de pinceles para pintura al óleo y acrílico', 10, 200, 12.99, 'Set', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1009, 'Bloc de dibujo Canson XL', 'Canson', 'Bloc de dibujo de 50 hojas, tamaño A4', 11, 150, 8.49, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1010, 'Tijeras Fiskars', 'Fiskars', 'Tijeras de acero inoxidable, 21cm', 12, 250, 7.99, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1011, 'Set de Arte Prismacolor', 'Prismacolor', 'Set de 24 lápices de colores de calidad profesional', 13, 100, 49.99, 'Set', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1012, 'Plastilina Play-Doh', 'Hasbro', 'Plastilina no tóxica para niños, paquete de 10 colores', 15, 300, 15.99, 'Paquete', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1013, 'Tijeras para manualidades', 'Fiskars', 'Tijeras de precisión para cortes detallados', 16, 250, 9.99, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1014, 'Cuaderno Oxford', 'Oxford', 'Cuaderno de 100 hojas, tapa dura', 17, 1000, 3.99, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1015, 'Mochila escolar Jansport', 'Jansport', 'Mochila resistente con varios compartimentos', 19, 500, 39.99, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1016, 'Bolígrafo Bic Cristal', 'Bic', 'Bolígrafo de tinta azul, pack de 5 unidades', 23, 1000, 2.99, 'Paquete', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1017, 'Cartucho de tinta Epson 664', 'Epson', 'Cartucho de tinta compatible con impresoras Epson', 24, 200, 16.99, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1018, 'Cinta adhesiva Scotch', '3M', 'Cinta adhesiva de 18mm x 25m, transparente', 27, 1500, 3.49, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1019, 'Mueble de oficina Sit Stand', 'Sit Stand', 'Mueble ajustable para oficina, escritorio de pie', 28, 30, 199.99, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1020, 'Agenda Moleskine', 'Moleskine', 'Agenda de cuero con espacio para notas, tamaño A5', 30, 500, 29.99, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1021, 'Cuaderno universitario', 'Ariston', 'Cuaderno espiral de 100 hojas, tamaño universitario', 31, 800, 6.99, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1022, 'Cartuchera Kipling', 'Kipling', 'Cartuchera con 3 compartimentos, color negro', 32, 200, 19.99, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1023, 'Bolsa de aseo personal', 'Tork', 'Bolsa de aseo con productos para baño y cuidado personal', 35, 500, 25.99, 'Paquete', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1024, 'Secadora de cabello Philips', 'Philips', 'Secadora de cabello profesional con 3 niveles de temperatura', 36, 300, 59.99, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1025, 'Aspiradora Rowenta', 'Rowenta', 'Aspiradora sin bolsa, tecnología ciclónica', 38, 150, 149.99, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1026, 'Contenedores plásticos Tupperware', 'Tupperware', 'Set de 5 contenedores plásticos herméticos', 40, 500, 24.99, 'Set', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1027, 'Envase descartable de polipropileno', 'Polysur', 'Envase descartable para comida, pack de 50 unidades', 41, 1000, 14.99, 'Paquete', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1028, 'Cinta de embalaje 3M', '3M', 'Cinta de embalaje de 50mm x 100m', 43, 2000, 7.49, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1029, 'Agua mineral San Luis', 'San Luis', 'Botella de 500ml de agua mineral natural', 44, 3000, 1.50, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1030, 'Galletas Príncipe', 'Marinela', 'Galletas rellenas con crema de chocolate', 45, 5000, 2.99, 'Paquete', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(10231, 'Detergente en polvo Omo', 'Omo', 'Detergente en polvo para lavado de ropa', 46, 1500, 7.49, 'Paquete', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(12351, 'Lápiz Faber-Castell HB', 'Faber-Castell', 'Lápiz HB para escritura general', 9, 300, 1.20, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(15782, 'Marcadores Stabilo Boss', 'Stabilo', 'Marcadores fluorescentes de alta calidad', 9, 150, 2.50, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(5433, 'Estuche de Colores Faber-Castell', 'Faber-Castell', 'Set de 24 lápices de colores', 9, 80, 15.00, 'Set', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1554, 'Sacapuntas Kum', 'Kum', 'Sacapuntas manual con depósito', 9, 200, 3.00, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1575, 'Lápices de Colores Stabilo', 'Stabilo', 'Set de 12 lápices de colores para dibujo', 9, 100, 10.00, 'Set', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(6156, 'Bolígrafo Layconsa', 'Layconsa', 'Bolígrafo de tinta azul', 9, 500, 1.50, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(3157, 'Marcadores Sharpie', 'Sharpie', 'Marcadores permanentes de punta fina', 9, 120, 3.00, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(2158, 'Bolígrafo Paper Mate', 'Paper Mate', 'Bolígrafo de gel con tinta de secado rápido', 9, 250, 2.00, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1559, 'Carpeta Ove', 'Ove', 'Carpeta de anillas con 3 ganchos', 27, 150, 5.00, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1630, 'Goma de borrar Vinifan', 'Vinifan', 'Goma de borrar blanca para lápiz', 9, 500, 0.50, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1616, 'Papel Bond Maped', 'Maped', 'Papel bond tamaño A4', 25, 400, 3.50, 'Paquete', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1756, 'Tijeras Artesco', 'Artesco', 'Tijeras para uso escolar', 9, 120, 4.00, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(16343, 'Lápiz Staedtler', 'Staedtler', 'Lápiz de dibujo 2B', 9, 200, 1.80, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(16434, 'Cuaderno Loro 100 Hojas', 'Loro', 'Cuaderno universitario con 100 hojas', 18, 300, 2.50, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1625, 'Cuaderno Justus 200 Hojas', 'Justus', 'Cuaderno universitario con 200 hojas', 18, 180, 4.00, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(15466, 'Cuaderno Minerva 100 Hojas', 'Minerva', 'Cuaderno con tapas duras y 100 hojas', 18, 250, 3.00, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1367, 'Cuaderno College 200 Hojas', 'College', 'Cuaderno con 200 hojas de alta calidad', 18, 150, 5.00, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1268, 'Carpeta A4 Loro', 'Loro', 'Carpeta con anillas tamaño A4', 27, 100, 6.00, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(16549, 'Bolígrafo Stabilo Point 88', 'Stabilo', 'Bolígrafo de punta fina para escribir y dibujar', 9, 400, 1.50, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1170, 'Marcadores Maped', 'Maped', 'Marcadores lavables para uso escolar', 9, 200, 3.00, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(5171, 'Lápiz de Colores Layconsa', 'Layconsa', 'Set de 12 lápices de colores de buena calidad', 9, 150, 8.00, 'Set', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1762, 'Papel A4 Vinifan', 'Vinifan', 'Papel A4 de 75 gramos', 25, 350, 2.80, 'Paquete', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1673, 'Goma de borrar Maped', 'Maped', 'Goma de borrar de caucho suave', 9, 300, 0.80, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1774, 'Carpeta de Palanca Ove', 'Ove', 'Carpeta de palanca con anillas metálicas', 27, 80, 7.00, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1675, 'Lápices de Colores Maped', 'Maped', 'Set de 12 lápices de colores', 9, 200, 5.00, 'Set', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(89567, 'Bolígrafo Kum', 'Kum', 'Bolígrafo de tinta negra con diseño ergonómico', 9, 450, 1.80, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1767, 'Plumones Sharpie', 'Sharpie', 'Plumones permanentes para superficies varias', 9, 100, 4.50, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1778, 'Bolígrafo Stabilo', 'Stabilo', 'Bolígrafo con tinta de gel en varios colores', 9, 300, 2.00, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(17569, 'Cuaderno College 100 Hojas', 'College', 'Cuaderno con 100 hojas', 18, 350, 3.00, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1880, 'Goma de borrar Staedtler', 'Staedtler', 'Goma de borrar de precisión para artistas', 9, 180, 1.50, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(18451, 'Marcadores Stabilo Swing Cool', 'Stabilo', 'Marcadores finos de colores brillantes', 9, 250, 2.80, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(18262, 'Bolígrafo Paper Mate InkJoy', 'Paper Mate', 'Bolígrafo de gel con tinta de secado rápido', 9, 350, 2.20, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(12383, 'Tijeras Faber-Castell', 'Faber-Castell', 'Tijeras para uso escolar con punta redonda', 9, 150, 5.00, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(51844, 'Carpeta Archivadora Maped', 'Maped', 'Carpeta archivadora con anillas metálicas', 27, 90, 7.00, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(18685, 'Set de lápices de colores Staedtler', 'Staedtler', 'Set de 24 lápices de colores profesionales', 9, 70, 18.00, 'Set', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1864, 'Cuaderno Minerva 80 Hojas', 'Minerva', 'Cuaderno con 80 hojas rayadas', 18, 220, 2.50, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1455, 'Lapicero Artesco', 'Artesco', 'Lapicero con 10 colores', 9, 200, 4.50, 'Set', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1824, 'Carpeta de Anillas Stabilo', 'Stabilo', 'Carpeta de anillas con 2 compartimentos', 27, 120, 6.00, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1894, 'Papel Bond Justus', 'Justus', 'Papel bond tamaño A4, 500 hojas', 25, 300, 6.00, 'Paquete', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1978, 'Marcadores de Pizarra Maped', 'Maped', 'Marcadores de pizarra para escribir y borrar', 9, 100, 5.50, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(19178, 'Tijeras de Dibujo Kum', 'Kum', 'Tijeras para recortar con precisión', 9, 80, 7.00, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(19482, 'Cuaderno Loro 200 Hojas', 'Loro', 'Cuaderno universitario con 200 hojas rayadas', 18, 250, 4.50, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(19983, 'Borrador de Pizarra Stabilo', 'Stabilo', 'Borrador para pizarra blanca', 9, 150, 4.00, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(19154, 'Carpeta de Anillas Justus', 'Justus', 'Carpeta de anillas con 3 compartimentos', 27, 80, 6.50, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(32195, 'Goma de borrar Kum', 'Kum', 'Goma de borrar de calidad premium', 9, 300, 1.00, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1961, 'Lápices de Colores Justus', 'Justus', 'Set de 12 lápices de colores', 9, 120, 9.00, 'Set', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(19721, 'Carpeta Ove A4', 'Ove', 'Carpeta A4 con anillas metálicas', 27, 110, 5.00, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(19118, 'Bolígrafo Sharpie Fine', 'Sharpie', 'Bolígrafo permanente con tinta de secado rápido', 9, 250, 3.20, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(1929, 'Cuaderno College 120 Hojas', 'College', 'Cuaderno con 120 hojas rayadas', 18, 150, 4.00, 'Unidad', 1);
insert into Producto(codigo, nombre, marca, descripcion, subcategoria_id, stock, precio_unitario, unidad_medida, estado) values(20210, 'Set de Marcadores Stabilo Pen 68', 'Stabilo', 'Set de 10 marcadores de punta gruesa para escribir', 9, 90, 15.00, 'Set', 1);

insert into sucursal(ciudad, direccion, correo) values('ATE', 'Av. Nicolás Ayllón 4770, Real Plaza Puruchuco', 'tdmallpuruchuco@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('ATE', 'Carretera Central 6.5 - Mz E Lote 11-12', 'tdate@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('BARRANCO', 'Av. Miguel Grau 361', 'tdbarranco@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('BREÑA', 'Av. Venezuela 727', 'tdbrena@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('BREÑA', 'Av. Brasil 778, La Rambla', 'tdrambrasil@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('CALLAO', 'Av. Argentina 3093, Minka', 'tdminka@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('CALLAO', 'Av. Oscar Benavides 3866, Mall Bellavista', 'tdmallbellalvista@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('CERCADO DE LIMA', 'Jr. Ucayali 686', 'tducayali@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('CERCADO DE LIMA', 'Jr. Miró Quesada 268-270', 'tdmiroquesada@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('CERCADO DE LIMA', 'Jr. Ucayali 760', 'tdcapon@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('CERCADO DE LIMA', 'Av. Paruro 949', 'tdparuro@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('CERCADO DE LIMA', 'Jr. Andahuaylas 748', 'tdanda1@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('CERCADO DE LIMA', 'Jr. Andahuaylas 739', 'tdanda2@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('CERCADO DE LIMA', 'Jr. Andahuaylas 896', 'tdanda3@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('CERCADO DE LIMA', 'Jr. Montevideo 1105', 'tdmontevideo@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('CHORRILLOS', 'Av. Defensores Del Morro 985', 'tdchorrillos@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('CHORRILLOS', 'Av. Paseo de La República 900, Matellini', 'tdmatellini@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('COMAS', 'Av, Túpac Amaru 5981', 'tailoycomas@gmail.com');
insert into sucursal(ciudad, direccion, correo) values('COMAS', 'Av. Los Ángeles 602, Mall Plaza Comas', 'tlmallcomas@gmail.com');
insert into sucursal(ciudad, direccion, correo) values('COMAS', 'Av. Victor A. Belaúnde Oeste 500 Urb. Chacra Cerro', 'tdcomas@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('INDEPENDENCIA', 'Tomás Valle Túpac Amaru, Plaza Norte', 'tdplazanorte@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('INDEPENDENCIA', 'Av. Alfredo Mendional 3698, Mega Plaza', 'tdmegaindependencia@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('INDEPENDENCIA', 'Av. Gerardo Unger 3599 Urb. Panamericana Norte', 'tdindependencia@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('JESÚS MARÍA', 'Av. Arnaldo Márquez 1219', 'tdjesusmaria@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('JESÚS MARÍA', 'Av. Salaverry 2370, Real Plaza', 'tdsalaverry@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('LA MOLINA', 'Av. La Molina 1148', 'tdlamolina@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('LA MOLINA', 'Av. Raúl Ferrero 1314-1318', 'tdferrero@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('LINCE', 'Jr. Risso 391', 'tdlince@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('LINCE', 'Av. Arenales 788', 'tdarenales@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('LOS OLIVOS', 'Av. Naranjal 1083', 'tdolivos@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('MAGDALENA', 'Jr. Mariscal Castilla 665', 'tdmagdalena@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('MIRAFLORES', 'Calle Schell 241', 'tdmiraflores@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('MIRAFLORES', 'Av. José Pardo 186', 'tdpardo@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('MIRAFLORES', 'Av. Larco 299', 'tdlarco@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('MIRAFLORES', 'Av. Alfredo Benavides 1400', 'tdbenavides@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('MIRAFLORES', 'Av. Angamos Este 301', 'tdangamos@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('PUEBLO LIBRE', 'Av. Antonio José de Sucre 400', 'tdsucre@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('PUENTE PIEDRA', 'Av. Miguel Grau 227', 'tdpuentepiedra@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('SAN BORJA', 'Av. Aviación 2901', 'tdsanborja@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('SAN BORJA', 'Jr. Ucello 184', 'tducello@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('SAN ISIDRO', 'Calle Emilio Cavenecia 309', 'tdcavenecia@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('SAN ISIDRO', 'Av. República de Panamá 3581', 'tdsanisidro@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('SAN ISIDRO', 'Av. Las Camelias 450', 'tdcamelias@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('SAN JUAN DE LURIGANCHO', 'Av. Lurigancho 997-999 sub Lote 3 Urb. Zárate, Mall Aventura', 'tdmallsjl@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('SAN JUAN DE LURIGANCHO', 'Av. Próceres De La Independencia 2899', 'tdsanjuandelurigancho@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('SAN JUAN DE LURIGANCHO', 'Av. Próceres De La Independencia 118', 'tdsjlurigancho@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('SAN JUAN DE LURIGANCHO', 'Av. San Martín Mz. H Lt 13', 'tdcantogrande@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('SAN JUAN DE MIRAFLORES', 'Av. De Los Héroes 542', 'tdsanjuan@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('SAN JUAN DE MIRAFLORES', 'Caller Los Lirios 257, Mall del Sur', 'tdmalldelsur@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('SAN LUIS', 'Av. San Luis 1956-1958', 'tdsanluis@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('SAN MIGUEL', 'Av. La Marina 2382', 'tdsanmiguel@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('SAN MIGUEL', 'Av. La Marina 2000-2100, Plaza San Miguel', 'tdplazasanmiguel@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('SAN MARTÍN DE PORRES', 'Av. Perú 2098 Urb. Perú', 'tdsanmartin@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('SANTA ANITA', 'Av. Nicolás Ayllón, Mall Aventura', 'tdmallsantaanita@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('SANTA ANITA', 'Jr. Los Flamencos 238', 'tdsantaanita@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('SANTA ANITA', 'Av. Nugget 125', 'tdsantan@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('SURCO', 'Av, Caminos Del Inca 450', 'tdchacarilla@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('SURCO', 'Av. La Encalada 621', 'tdencalada@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('SURCO', 'Av. Los Próceres 215/221', 'tdbolichera@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('SURCO', 'Av. Benavides 5223', 'tdsurco@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('SURCO', 'Av. Aviación 5007', 'tdhiguereta@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('SURCO', 'Av. Javier Prado Este 4200, Jockey Plaza', 'tdjockey@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('SURQUILLO', 'Jr. Dante 885', 'tdsurquillo@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('VENTANILLA', 'Mz. C2 Lt. 14 Ex Zona Comercial Ventanilla', 'tlventanilla@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('VILLA EL SALVADOR', 'Parque Industrial De Villa El Salvador, Mz K2, Lt 5', 'tlvillaelsalvador@tailoy.com.pe');
insert into sucursal(ciudad, direccion, correo) values('VILLA EL SALVADOR', 'Av. Revolución Cd. 18 Mz. J Lt. 21 Sector 2 Gr. 9', 'tdvesalvador@tailoy.com.pe');
